/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountsList.java
 *
 * Created on 07/04/2011, 22:06:31
 */
package ui.core.containers;

import java.util.ArrayList;
import jaytter.api.Accounts;
import models.Account;
import ui.core.containers.accounts.AccountList;

/**
 *
 * @author joaoneto
 */
public final class AccountsList extends javax.swing.JPanel {

    /** Creates new form AccountsList */
    public AccountsList() {
        initComponents();
        addAccountsToList(  );

    }

    public void addAccountsToList(  )
    {
        AccountList a = new AccountList();
        this.add( a );
    }
    
    private void addAccountToPanel( AccountList ui )
    {
        add( ui );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        setBackground(java.awt.Color.cyan);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
