/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ui.core.containers;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import twitter4j.Status;

/**
 * TODO Esta classe deverá completar o esqueleto de Message, formando
 * um tweet completo.
 * 
 * Um tweet tem basicamente:
 * - autor (herda de Message)
 * - texto (herda de Message)
 * - timestamp (herda de Message)
 * - botão de RT, Quote (old RT), Favorite, Reply
 * @author samirfor
 */
public class Tweet extends javax.swing.JPanel {

    /** Creates new form Tweet */
    public Tweet() {
        initComponents();
    }
    
    public Tweet(Status status) {
        initComponents();
        loadProfileImage(status.getUser().getProfileImageURL());
        message.setText(status.getText());
    }
    
    private void loadProfileImage(URL source) {
        Image image = null;
        try {
            image = ImageIO.read(source);
        } catch (IOException ex) {
            Logger.getLogger(Tweet.class.getName()).log(Level.SEVERE, null, ex);
        }
        avatar.setIcon(new ImageIcon(image));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAvatar = new javax.swing.JPanel();
        avatar = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jPanelAvatar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelAvatar.setFocusable(false);
        jPanelAvatar.setMaximumSize(new java.awt.Dimension(48, 48));
        jPanelAvatar.setMinimumSize(new java.awt.Dimension(48, 48));

        avatar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        avatar.setMinimumSize(new java.awt.Dimension(48, 48));

        org.jdesktop.layout.GroupLayout jPanelAvatarLayout = new org.jdesktop.layout.GroupLayout(jPanelAvatar);
        jPanelAvatar.setLayout(jPanelAvatarLayout);
        jPanelAvatarLayout.setHorizontalGroup(
            jPanelAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAvatarLayout.createSequentialGroup()
                .add(avatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelAvatarLayout.setVerticalGroup(
            jPanelAvatarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAvatarLayout.createSequentialGroup()
                .add(avatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        message.setText("<html><p>O @zanata_arnos dissecou o Peñarol no Blog do Mauro Cezar. Leitura obrigatória para quem verá a final hoje: http://bit.ly/geFuSC.</p></html>");
        message.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(message, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(message)
                    .add(jPanelAvatar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JPanel jPanelAvatar;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
