package ui.core.containers.accounts;

import javax.swing.JFrame;
import models.Account;
import org.jaytter.model.user.TweetAccount;
import org.jaytter.ui.manager.account.JaytterUIAccountManager;
import ui.core.MainWindow;

public class AccountList extends javax.swing.JPanel {
    
    private JFrame parentFrame;

    /** Creates new form AccountList */
    public AccountList(JFrame parentFrame, Account account) {
        initComponents();
        this.parentFrame = parentFrame;
        this.account = account;
        this.accountName.setText(account.getName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaytter/images/intents-assets/intents-assets/bird/bird_gray/bird_32_gray.png"))); // NOI18N
        add(jLabel1);

        accountName.setFont(accountName.getFont().deriveFont(accountName.getFont().getStyle() | java.awt.Font.BOLD));
        add(accountName);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        add(buttonLogin);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        JaytterUIAccountManager.getInstance().setupAccount( new TweetAccount() );
    }//GEN-LAST:event_buttonLoginActionPerformed
    private Account account;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel accountName;
    public javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
