/*
 * AccountList.java
 *
 * Created on 07/04/2011, 22:14:35
 */
package ui.core.containers.accounts;

import jaytter.ConsumerTokens;
import models.Account;
import twitter4j.ResponseList;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.User;

/**
 *
 * @author joaoneto
 */
public class AccountList extends javax.swing.JPanel {

    /** Creates new form AccountList */
    public AccountList(Account account) {
        initComponents();
        this.account = account;
        this.accountName.setText(account.getName());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaytter/images/intents-assets/intents-assets/bird/bird_gray/bird_32_gray.png"))); // NOI18N
        add(jLabel1);

        accountName.setFont(accountName.getFont().deriveFont(accountName.getFont().getStyle() | java.awt.Font.BOLD));
        add(accountName);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        add(buttonLogin);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        System.out.println("Tentando logar na api: " + this.account.getUser());
        
        
        // Teste Pesquisa por Usuario
        Twitter twitter = new TwitterFactory().getInstance();
        twitter.setOAuthConsumer(ConsumerTokens.KEY, ConsumerTokens.SECRET);
        twitter.setOAuthAccessToken(account.getAccessToken());
        try {
            ResponseList<User> searchUsers = twitter.searchUsers("samir", 1);
            for(User user : searchUsers) {
                System.out.println(user.getName()+ " - " + user.getScreenName());
            }
        } catch(TwitterException te) {
            System.out.println(te.getMessage());
        }
        // FIM Teste Pesquisa por Usuario
        // Está funcionando!
        
        // TODO Abrir janela da principal com a timeline
    }//GEN-LAST:event_buttonLoginActionPerformed
    private Account account;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel accountName;
    public javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
