/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountList.java
 *
 * Created on 07/04/2011, 22:14:35
 */
package ui.core.containers.accounts;

/**
 *
 * @author joaoneto
 */
public class AccountList extends javax.swing.JPanel {

    /** Creates new form AccountList */
    public AccountList() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountName = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jaytter/images/intents-assets/intents-assets/bird/bird_gray/bird_32_gray.png"))); // NOI18N
        add(jLabel1);

        accountName.setFont(accountName.getFont().deriveFont(accountName.getFont().getStyle() | java.awt.Font.BOLD));
        accountName.setText("@joao_neto");
        add(accountName);

        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        add(buttonLogin);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel accountName;
    public javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
