/*
 * Copyright (C) 2011 joao-nb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AccountTweetForm.java
 *
 * Created on 29/06/2011, 03:12:25
 */
package org.jaytter.ui.account;

import org.jaytter.ui.manager.account.JaytterUIAccountManager;

/**
 *
 * @author joao-nb
 */
public class AccountTweetForm extends javax.swing.JPanel {

    /** Creates new form AccountTweetForm */
    public AccountTweetForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        userAvatar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTweet = new javax.swing.JTextArea();
        buttonTweet = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        userAvatar.setText("<html><img src=\"oi.png\" /></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.ipady = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(userAvatar, gridBagConstraints);

        textTweet.setColumns(20);
        textTweet.setRows(5);
        jScrollPane1.setViewportView(textTweet);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 284;
        gridBagConstraints.ipady = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 12);
        add(jScrollPane1, gridBagConstraints);

        buttonTweet.setText("Twittar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 236, 12, 12);
        add(buttonTweet, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTweet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textTweet;
    private javax.swing.JLabel userAvatar;
    // End of variables declaration//GEN-END:variables
}
